name: CI/CD Pipeline by Fortress Technologies Inc

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: "17"

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push k8cart
        working-directory: cart/
        run: |
          docker build -t iscanprint/k8cart:2.5 .
          docker push iscanprint/k8cart:2.5

      - name: Build and push k8catalogue
        working-directory: catalogue/
        run: |
          docker build -t iscanprint/k8catalogue:2.5 .
          docker push iscanprint/k8catalogue:2.5

      - name: Build and push k8dispatch
        working-directory: dispatch/ 
        run: |
          docker build -t iscanprint/k8dispatch:2.5 .
          docker push iscanprint/k8dispatch:2.5

      - name: Build and push k8fluentd
        working-directory: fluentd/
        run: |
          docker build -t iscanprint/k8fluentd:2.5 .
          docker push iscanprint/k8fluentd:2.5

      - name: Build and push load-gen
        working-directory: load-gen/
        run: |
          docker build -t iscanprint/k8load-gen:2.5 .
          docker push iscanprint/k8load-gen:2.5

      - name: Build and push mongo
        working-directory: mongo/
        run: |
          docker build -t iscanprint/k8mongo:2.5 .
          docker push iscanprint/k8mongo:2.5

      - name: Build and push mysql
        working-directory: mysql/
        run: |
          docker build -t iscanprint/k8mysql:2.5 .
          docker push iscanprint/k8mysql:2.5

      - name: Build and push payment 
        working-directory: payment/ 
        run: |
          docker build -t iscanprint/k8payment:2.5 .
          docker push iscanprint/k8payment:2.5

      - name: Build and push ratings 
        working-directory: ratings/
        run: |
          docker build -t iscanprint/k8ratings:2.5 .
          docker push iscanprint/k8ratings:2.5

      - name: Build and push shipping
        working-directory: shipping/
        run: |
          docker build -t iscanprint/k8shipping:2.5 . -f Dockerfile1
          docker push iscanprint/k8shipping:2.5

      - name: Build and push user
        working-directory: user/
        run: |
          docker build -t iscanprint/k8user:2.5 .
          docker push iscanprint/k8user:2.5

      - name: Build and push web
        working-directory: web/
        run: |
          docker build -t iscanprint/k8web:2.5 .
          docker push iscanprint/k8web:2.5
