name: CI/CD Pipeline by Fortress Technologies Inc

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: "17"

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker images
        run: |
          components=("cart" "catalogue" "dispatch" "fluentd" "load-gen" "mongo" "mysql" "payment" "ratings" "shipping" "user" "web")

          for component in "${components[@]}"
          do
            echo "Building and pushing iscanprint/k8${component}svc:2.5"
            docker build -t "iscanprint/k8${component}svc:2.5" "./${component}/"
            docker push "iscanprint/k8${component}svc:2.5"
          done
