name: Deploy and Test Docker Compose

on:
  push:
    branches:
      - master  # Adjust this branch if necessary
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Update and upgrade system packages
      run: |
        sudo apt-get update
        sudo apt-get upgrade -y

    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose --version  # Verify installation

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Deploy with Docker Compose
      run: |
        docker-compose build
        docker-compose push
        docker-compose pull  # Ensure images are up-to-date
        docker-compose up -d  # Deploy the application in detached mode
      env:
        DOCKER_BUILDKIT: 1

    - name: Clean up unused Docker resources
      run: |
        docker system prune -f
