name: Deploy and Test Docker Compose

on:
  push:
    branches:
      - master  # Adjust this branch if necessary
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Update and upgrade system packages
      run: |
        sudo apt-get update
        sudo apt-get upgrade -y

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Deploy with Docker Compose
    
      run: |
        docker-compose pull  # Ensure images are up-to-date
        docker-compose up -d  # Deploy the application in detached mode
      env:
        DOCKER_BUILDKIT: 1

    - name: Wait for services to be ready
      run: sleep 30  # Wait for 30 seconds to ensure the services are up and running

    - name: Run application tests
      run: |
        # Replace with your specific test commands
        curl --fail http://localhost:8080/health || exit 1
        # Example: Run additional tests if needed

    - name: Clean up unused Docker resources
      run: |
        docker system prune -f
